import './js/components/theme';
import './js/components/categories';
// import './js/components/articles';
import './js/components/calendar';
import './js/components/favorites';
import './js/components/header';
import './js/components/pagination';
// import './js/components/read';
import './js/components/weather';
import './js/components/burger-menu';
import './js/components/dataBase/auth';
import './js/components/dataBase/setDatabase';
import './js/components/dataBase/register';
import './js/components/dataBase/modal';
import './js/components/dataBase/authForm';
import './js/components/input';
// import './js/common/markup_template';
import './js/common/weather_API';
